---
version: "3.8"

services:
  tengine-http:
    #image: axizdkr/tengine:3.1.0
    build:
      context: .  # 构建上下文目录（当前目录）
      dockerfile: Dockerfile  # 默认可以省略，当文件名是 Dockerfile 时
      args:
        - TENGINE_VERSION=3.1.0
    container_name: tengine-http
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d/
    networks:
      - web-in

networks:
  web-in:
    name: web-in
